### ISSUE TITLE
fails on 2.6.9

### ISSUE THREAD

**Issue by DarkSideGeek** [jbbarth/redmine_reminders#2]
````
rake aborted!
Redmine::PluginNotFound: Redmine::PluginNotFound
/var/www/apps/redmine-2.6.9/lib/redmine/plugin.rb:118:in `find'
/var/www/apps/redmine-2.6.9/lib/redmine/plugin.rb:246:in `requires_redmine_plugin'
/var/www/apps/redmine-2.6.9/plugins/redmine_reminders/init.rb:10:in `block in <top (required)>'
/var/www/apps/redmine-2.6.9/lib/redmine/plugin.rb:75:in `instance_eval'
/var/www/apps/redmine-2.6.9/lib/redmine/plugin.rb:75:in `register'
/var/www/apps/redmine-2.6.9/plugins/redmine_reminders/init.rb:1:in `<top (required)>'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `block in require'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:236:in `load_dependency'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require'
/var/www/apps/redmine-2.6.9/lib/redmine/plugin.rb:150:in `block in load'
/var/www/apps/redmine-2.6.9/lib/redmine/plugin.rb:141:in `each'
/var/www/apps/redmine-2.6.9/lib/redmine/plugin.rb:141:in `load'
/var/www/apps/redmine-2.6.9/config/initializers/30-redmine.rb:19:in `<top (required)>'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:245:in `load'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:245:in `block in load'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:236:in `load_dependency'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:245:in `load'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/railties-3.2.22/lib/rails/engine.rb:593:in `block (2 levels) in <class:Engine>'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/railties-3.2.22/lib/rails/engine.rb:592:in `each'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/railties-3.2.22/lib/rails/engine.rb:592:in `block in <class:Engine>'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/railties-3.2.22/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/railties-3.2.22/lib/rails/initializable.rb:30:in `run'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/railties-3.2.22/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/railties-3.2.22/lib/rails/initializable.rb:54:in `each'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/railties-3.2.22/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/railties-3.2.22/lib/rails/application.rb:136:in `initialize!'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/railties-3.2.22/lib/rails/railtie/configurable.rb:30:in `method_missing'
/var/www/apps/redmine-2.6.9/config/environment.rb:14:in `<top (required)>'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `block in require'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:236:in `load_dependency'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/railties-3.2.22/lib/rails/application.rb:103:in `require_environment!'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/railties-3.2.22/lib/rails/application.rb:305:in `block (2 levels) in initialize_tasks'
/usr/local/rvm/gems/ruby-1.9.3-p429/bin/ruby_noexec_wrapper:14:in `eval'
/usr/local/rvm/gems/ruby-1.9.3-p429/bin/ruby_noexec_wrapper:14:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
````

**Comment by nanego** [comment]
You should first install this plugin: https://github.com/jbbarth/redmine_base_deface
I will update the installation section in the Readme file.

**Comment by DarkSideGeek** [comment]
Confirmed. I'm past the install phase, and I see the docs have already been updated. Not out of the woods, but we can close this one...
